config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController<ApplicationController

    def index
        @users=User.all
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end

    def new
        @user=User.new
    end

    def create
        @user=User.new(user_params)

        
        if @user.save!
            redirect_to root_path
        end
    end

    def edit
        @user=User.find(params[:id])
    end

    def update
        @user=User.find(params[:id])
        @user.update(user_params)
        redirect_to root_path
    end

    def destroy
        @user= User.find(params[:id])
        @user.destroy
        redirect_to root_path
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h2><%= link_to 'new user', new_user_path %></h2>
<br>
<h2>print all users</h2>
<div class="container">
    <div class="row">
        <% @users.each do |p|%>
            <div class="col-md-3">
                <div class="row">
                    <div class="col-6">
                        <%= image_tag p.avatar, class: "img" %>
                    </div>
                    <div class="col-6">
                        <%= p.name %>
                        <br>
                        <%= link_to 'edit' , edit_user_path(p) %>
                        <%= button_to 'delete' , user_path(p), method: :delete %>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activestorage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<%=form_with model: @user do |form| %>
   
    
    <div class="field">
        <%= form.label :name %><br />
        <%= form.text_field :name ,class: 'form-control border-warning'%>
    </div>
   
    <div class="field">
        <%= form.label :avatar %><br />
        <%= form.file_field :avatar  %>
        
    </div>
    <div>
      <%= form.submit "save",class: "btn btn-sm btn-outline-primary"%>

    </div>



<%end%>

app/views/user/new.html.erb
<%=form_with model: @user do |form| %>
   
    
    <div class="field">
        <%= form.label :name %><br />
        <%= form.text_field :name ,class: 'form-control border-warning'%>
    </div>
   
    <div class="field">
        <%= form.label :avatar %><br />
        <%= form.file_field :avatar  %>
        
    </div>
    <div>
      <%= form.submit "save",class: "btn btn-sm btn-outline-primary"%>

    </div>



<%end%>